POO1_T1_Yauli Misco Paul/POO1_T1_Yauli Misco Paul/Controllers/PlanillaController.cs
using POO1_T1_Yauli_Misco_Paul.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POO1_T1_Yauli_Misco_Paul.Controllers
{
    public class PlanillaController : Controller
    {
        public static int contador = 0;
        public static List<Asistente> listAsistente;

        public PlanillaController()
        {
            if (listAsistente == null)
            {
                listAsistente = new List<Asistente>();
                listAsistente.Add(new Asistente()
                {
                    dniTrab = "70184952",
                    apeTrab = "Yauli",
                    nomTrab = "Paul",
                    fecContrato = new DateTime(2000, 5, 15),
                    categoriaTrab = "D",
                    numeroHijos = 1,
                    gradoEducacion = "superior",
                });
                listAsistente.Add(new Asistente()
                {
                    dniTrab = "78459517",
                    apeTrab = "Chavez",
                    nomTrab = "Brandon",
                    fecContrato = new DateTime(2005, 5, 15),
                    categoriaTrab = "B",
                    numeroHijos = 4,
                    gradoEducacion = "secundaria",
                });
                contador = listAsistente.Count;
            }

            Debug.WriteLine("Ini LaptopController");
        }

        // GET: Planilla
        public ActionResult Index()
        {
            ViewBag.dniTrab = "80485178";
            ViewBag.apeTrab = "Yauli";
            ViewBag.nomTrab = "Paul";
            ViewBag.fecContrato = "2023-10-01";
            ViewBag.categoriaTrab = "D";

            return View();
        }

        [HttpGet]
        public ActionResult CreateTrabajador()
        {
            Trabajador objTrab = new Trabajador();
            return View(objTrab);
        }

        [HttpPost]
        public ActionResult CreateTrabajador(Trabajador objTrab)
        {

            Debug.WriteLine("Dni Trabajador : " + objTrab.dniTrab);
            Debug.WriteLine("Apellido : " + objTrab.apeTrab);
            Debug.WriteLine("Nombre : " + objTrab.nomTrab);
            Debug.WriteLine("Fecha Contrato : " + objTrab.fecContrato);
            Debug.WriteLine("Categoria : " + objTrab.categoriaTrab);

            ViewBag.SueldoBasico = objTrab.calculoSueldoBasico();
            ViewBag.Bonificacion = objTrab.calculoBonificacionCategoria();
            ViewBag.Monto = objTrab.Monto();

            return View(objTrab);
        }

        [HttpGet]
        public ActionResult CreateAsistente()
        {
            return View(new Asistente());
        }

        [HttpPost]
        public ActionResult CreateAsistente(Asistente objAsist)
        {
            Debug.WriteLine("Dni Trabajador : " + objAsist.dniTrab);
            Debug.WriteLine("Apellido : " + objAsist.apeTrab);
            Debug.WriteLine("Nombre : " + objAsist.nomTrab);
            Debug.WriteLine("Fecha Contrato : " + objAsist.fecContrato);
            Debug.WriteLine("Categoria : " + objAsist.categoriaTrab);
            Debug.WriteLine("Numero de hijos : " + objAsist.numeroHijos);
            Debug.WriteLine("Grado Educación : " + objAsist.gradoEducacion);

            string mensaje;
            Asistente asistExistente = listAsistente.Find(x => x.dniTrab == objAsist.dniTrab);
            if (asistExistente == null)
            {
                listAsistente.Add(objAsist);
                contador++;
                mensaje = "El asistente fue agregado a la lista";
                Debug.WriteLine("El dni ingresado no existe");
            }
            else
            {
                mensaje = "El asistente ya existe";
                Debug.WriteLine("El dni ingresado existe");
                Debug.WriteLine("Dni : " + asistExistente.dniTrab);
            }

            ViewBag.ContadorRegistros = contador;
            ViewBag.MensajeValidacion = mensaje;
            ViewBag.SueldoBasico = objAsist.calculoSueldoBasico();
            ViewBag.Escolaridad = objAsist.calculoEscolaridad();
            ViewBag.BonificaciónEspecial = objAsist.calculoBonificacionEspecial();
            ViewBag.Monto = objAsist.Monto();
            Debug.WriteLine("Total Registros : " + listAsistente.Count);
            return View(objAsist);
        }

        public ActionResult ListadoAsistente()
        {
            ViewBag.CantidadRegistrados = listAsistente.Count;
            return View(listAsistente);
        }
    }
}

POO1_T1_Yauli Misco Paul/POO1_T1_Yauli Misco Paul/Views/Planilla/CreateAsistente.cshtml
@model POO1_T1_Yauli_Misco_Paul.Models.Asistente

@{
    ViewBag.Title = "CreateAsistente";
}

<h2>CreateAsistente</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Asistente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label>Dni Asistente</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.dniTrab, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dniTrab, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Apellido Asistente</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.apeTrab, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.apeTrab, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Nombre Asistente</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomTrab, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nomTrab, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Fecha Contrato</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecContrato, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.fecContrato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Categoria</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoriaTrab, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoriaTrab, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Numero de hijos</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.numeroHijos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numeroHijos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Grado Educacion</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.gradoEducacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gradoEducacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mt-2">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <label class="fw-bold">Contador: </label> @ViewBag.ContadorRegistros <br />
    <label class="fw-bold">Mensaje: </label> @ViewBag.MensajeValidacion <br />
    <label class="fw-bold">Sueldo Basico: </label> @ViewBag.SueldoBasico <br />
    <label class="fw-bold">Escolaridad: </label> @ViewBag.Escolaridad <br />
    <label class="fw-bold">Bonificacion Especial: </label> @ViewBag.BonificaciónEspecial <br />
    <label class="fw-bold">Monto: </label> @ViewBag.Monto <br />
</div>

<div>
    @Html.ActionLink("Lista de Asistentes", "ListadoAsistente", "Planilla")
</div>

POO1_T1_Yauli Misco Paul/POO1_T1_Yauli Misco Paul/Views/Planilla/CreateTrabajador.cshtml
@model POO1_T1_Yauli_Misco_Paul.Models.Trabajador

@{
    ViewBag.Title = "CreateTrabajador";
}

<h2>Create Trabajador</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Trabajador</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
           <label>Dni Trabajador</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.dniTrab, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dniTrab, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Apellido</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.apeTrab, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.apeTrab, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Nombre</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomTrab, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nomTrab, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Fecha Contrato</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecContrato, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.fecContrato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Categoria</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoriaTrab, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.categoriaTrab, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mt-2">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <label class="fw-bold">Sueldo Basico: </label> @ViewBag.SueldoBasico <br />
    <label class="fw-bold">Bonificacion: </label> @ViewBag.Bonificacion <br />
    <label class="fw-bold">Monto: </label> @ViewBag.Monto <br />
</div>

<div>
    @Html.ActionLink("Inicio", "", "" )
</div>

POO1_T1_Yauli Misco Paul/POO1_T1_Yauli Misco Paul/Views/Planilla/ListadoAsistente.cshtml
@model IEnumerable<POO1_T1_Yauli_Misco_Paul.Models.Asistente>

@{
    ViewBag.Title = "ListadoAsistente";
}

<h2>Listado Asistente</h2>

<p>
    @Html.ActionLink("Crear Asistente", "CreateAsistente", "Planilla")
</p>
<table class="table">
    <tr>
        <th>
            Dni
        </th>
        <th>
            Apellido
        </th>
        <th>
            Nombre
        </th>
        <th>
            Fecha Contrato
        </th>
        <th>
            Categoria
        </th>
        <th>
           Numero Hijos
        </th>
        <th>
           Grado Educacion
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.dniTrab)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.apeTrab)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nomTrab)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fecContrato)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.categoriaTrab)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.numeroHijos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.gradoEducacion)
        </td>
    </tr>
}
</table>
<div>
    <label>Cantidad de registrados: </label> @ViewBag.CantidadRegistrados <br />
</div>